//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_for_WOT.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quiz_for_WOT.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings, soldier! Ready to start the battle?.
        /// </summary>
        internal static string AppHello {
            get {
                return ResourceManager.GetString("AppHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz for WOT.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAboutApp {
            get {
                return ResourceManager.GetString("MenuAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our projects.
        /// </summary>
        internal static string MenuAnotherProject {
            get {
                return ResourceManager.GetString("MenuAnotherProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string MenuCopyright {
            get {
                return ResourceManager.GetString("MenuCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string MenuGame {
            get {
                return ResourceManager.GetString("MenuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My records.
        /// </summary>
        internal static string MenuStatictics {
            get {
                return ResourceManager.GetString("MenuStatictics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string MenuStorage {
            get {
                return ResourceManager.GetString("MenuStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string MenuStore {
            get {
                return ResourceManager.GetString("MenuStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string NavigationToMenu {
            get {
                return ResourceManager.GetString("NavigationToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Tank Quiz - added a new level of the game, updated storyline, enhanced graphics - lots of positive and fun will not leave you indifferent!
        ///
        ///Tanks guess from the description or image.
        ///
        ///Know your limits!
        ///
        ///And then go out beyond them!
        ///
        ///The game contains all technics of World of Tanks computer game.
        ///
        ///Complete the game, type the record and become the best of the best!
        ///
        ///So what are you waiting for?.
        /// </summary>
        internal static string PageAboutApp {
            get {
                return ResourceManager.GetString("PageAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Tank Quiz - added a new level of the game, updated storyline, enhanced graphics - lots of positive and fun will not leave you indifferent!
        ///
        ///Tanks guess from the description or image.
        ///
        ///Know your limits!
        ///
        ///And then go out beyond them!
        ///
        ///The game contains all technics of World of Tanks computer game.
        ///
        ///Complete the game, type the record and become the best of the best!
        ///
        ///So what are you waiting for?.
        /// </summary>
        internal static string PageAboutAppText {
            get {
                return ResourceManager.GetString("PageAboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show app.
        /// </summary>
        internal static string PageAnotherProjectButtonOpen {
            get {
                return ResourceManager.GetString("PageAnotherProjectButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://itunes.apple.com/us/app/my-habits-step-by-step/id1135293904.
        /// </summary>
        internal static string PageAnotherProjectLink {
            get {
                return ResourceManager.GetString("PageAnotherProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control your habits - one of the main challenges facing the human striving for personal growth and self-development. Habits determine the nature, condition of the body, up to 40% of our daily activities. By changing just a few habits can change throughout his life.
        ///You may be accustomed to get up early to run, just to sit, to eat, to think positively, to meditate, to streamline the daily routine and more. A chance meeting can change the fate. Change only one habit change your whole future life.
        ///
        ///So what  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageAnotherProjectText {
            get {
                return ResourceManager.GetString("PageAnotherProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle tasks to get experience:.
        /// </summary>
        internal static string PageBattleTasksHello {
            get {
                return ResourceManager.GetString("PageBattleTasksHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is NOT a development of Wargaming.net. Application is made in accordance with Wargaming Developer Partner Program rules: http://eu.wargaming.net/developers/documentation/rules/rules/.
        /// </summary>
        internal static string PageCopyrightText {
            get {
                return ResourceManager.GetString("PageCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is NOT a development of Wargaming.net. Application is made in accordance with Wargaming Developer Partner Program rules: http://eu.wargaming.net/developers/documentation/rules/rules/.
        /// </summary>
        internal static string PageCopyrightText1 {
            get {
                return ResourceManager.GetString("PageCopyrightText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get scores.
        /// </summary>
        internal static string PageGameGetMoney {
            get {
                return ResourceManager.GetString("PageGameGetMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Battle.
        /// </summary>
        internal static string PageGameStart {
            get {
                return ResourceManager.GetString("PageGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose.
        /// </summary>
        internal static string PageLoseTitle {
            get {
                return ResourceManager.GetString("PageLoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global record: 576.
        /// </summary>
        internal static string PageStatisticsGlobalRating {
            get {
                return ResourceManager.GetString("PageStatisticsGlobalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All experience.
        /// </summary>
        internal static string PageStatisticsLabelAllExperience {
            get {
                return ResourceManager.GetString("PageStatisticsLabelAllExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All money.
        /// </summary>
        internal static string PageStatisticsLabelAllMoney {
            get {
                return ResourceManager.GetString("PageStatisticsLabelAllMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All questions.
        /// </summary>
        internal static string PageStatisticsLabelAllQuestion {
            get {
                return ResourceManager.GetString("PageStatisticsLabelAllQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string PageStatisticsLabelFalseQuestion {
            get {
                return ResourceManager.GetString("PageStatisticsLabelFalseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My records.
        /// </summary>
        internal static string PageStatisticsLabelRecords {
            get {
                return ResourceManager.GetString("PageStatisticsLabelRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string PageStatisticsLabelTrueQuestion {
            get {
                return ResourceManager.GetString("PageStatisticsLabelTrueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string PageStatisticsTitle {
            get {
                return ResourceManager.GetString("PageStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Won.
        /// </summary>
        internal static string PageWinGameTitle {
            get {
                return ResourceManager.GetString("PageWinGameTitle", resourceCulture);
            }
        }
    }
}
